/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MainFrame;

import javax.swing.JOptionPane;

/**
 *
 * @author Mauro
 */
public class Ejercicio2 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio2
     */
    public Ejercicio2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BFahrenheit = new javax.swing.JRadioButton();
        BKelvin = new javax.swing.JRadioButton();
        BCelsius = new javax.swing.JRadioButton();
        BRadianes = new javax.swing.JRadioButton();
        IngresoTemperatura = new javax.swing.JTextField();
        TextoTemperatura = new javax.swing.JLabel();
        EligeTemperatura = new javax.swing.JComboBox<>();
        BConvertir = new javax.swing.JButton();
        TextoGrados = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel2.setText("Ingrese la Temperatura");

        BFahrenheit.setText("A Fahrenheit");
        BFahrenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFahrenheitActionPerformed(evt);
            }
        });

        BKelvin.setText("A Kelvin");
        BKelvin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BKelvinActionPerformed(evt);
            }
        });

        BCelsius.setText("A Celsius");
        BCelsius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCelsiusActionPerformed(evt);
            }
        });

        BRadianes.setText("A Radianes");
        BRadianes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRadianesActionPerformed(evt);
            }
        });

        IngresoTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresoTemperaturaActionPerformed(evt);
            }
        });

        TextoTemperatura.setText("Temperatura");

        EligeTemperatura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fahrenheit", "Celsius", "Kelvin", "Radianes" }));
        EligeTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EligeTemperaturaActionPerformed(evt);
            }
        });

        BConvertir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-aprobar-y-actualizar-48.png"))); // NOI18N
        BConvertir.setText("Convertir");
        BConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BConvertirActionPerformed(evt);
            }
        });

        TextoGrados.setText("Grados");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        jLabel1.setText("Conversor de Temperatura");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TextoTemperatura)
                                .addGap(18, 18, 18)
                                .addComponent(EligeTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(IngresoTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TextoGrados))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BKelvin)
                                    .addComponent(BFahrenheit))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BRadianes)
                                    .addComponent(BCelsius)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BConvertir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IngresoTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoTemperatura)
                    .addComponent(EligeTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoGrados))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BFahrenheit)
                        .addGap(18, 18, 18)
                        .addComponent(BKelvin))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BCelsius)
                        .addGap(18, 18, 18)
                        .addComponent(BRadianes)))
                .addGap(18, 18, 18)
                .addComponent(BConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngresoTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresoTemperaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngresoTemperaturaActionPerformed

    private void BCelsiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCelsiusActionPerformed
        if(BKelvin.isSelected() || BFahrenheit.isSelected() || BRadianes.isSelected()){
            BKelvin.setSelected(false);
            BFahrenheit.setSelected(false);
            BRadianes.setSelected(false);
        }
    }//GEN-LAST:event_BCelsiusActionPerformed

    private void BFahrenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFahrenheitActionPerformed
        if(BKelvin.isSelected() || BRadianes.isSelected() || BCelsius.isSelected()){
            BKelvin.setSelected(false);
            BRadianes.setSelected(false);
            BCelsius.setSelected(false);
        }
    }//GEN-LAST:event_BFahrenheitActionPerformed

    private void BKelvinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BKelvinActionPerformed
        if(BRadianes.isSelected() || BFahrenheit.isSelected() || BCelsius.isSelected()){
            BRadianes.setSelected(false);
            BFahrenheit.setSelected(false);
            BCelsius.setSelected(false);
        }
    }//GEN-LAST:event_BKelvinActionPerformed

    private void BRadianesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRadianesActionPerformed
        if(BKelvin.isSelected() || BFahrenheit.isSelected() || BCelsius.isSelected()){
            BKelvin.setSelected(false);
            BFahrenheit.setSelected(false);
            BCelsius.setSelected(false);
        }
    }//GEN-LAST:event_BRadianesActionPerformed

    private void BConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BConvertirActionPerformed
        Double tempCambiada = 0.0;
        switch (EligeTemperatura.getSelectedIndex()) {
            case 0:{
                //Aca hago Fahrenheit a x
                double fahrenheit = (Double.parseDouble(IngresoTemperatura.getText()));
                if(BCelsius.isSelected()){
                    tempCambiada = (fahrenheit-32) * 5/9;
                    JOptionPane.showMessageDialog(this, "De Fahrenheit a Celsius es de\n" + String.format("%.2f", tempCambiada), "Convertido con exito", JOptionPane.INFORMATION_MESSAGE);
                }else if(BKelvin.isSelected()){
                    tempCambiada = (Double.parseDouble(IngresoTemperatura.getText()) - 32) * 5/9 + 273.15;
                    JOptionPane.showMessageDialog(this, "De Fahrenheit a Kelvin es de\n" + String.format("%.2f", tempCambiada), "Convertido con exito", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(this, "La combinación no se puede hacer", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
                break;
            }case 1:{
                if(BFahrenheit.isSelected()){
                    tempCambiada = Double.parseDouble(IngresoTemperatura.getText()) * 9/5 + 32;
                    JOptionPane.showMessageDialog(this, "De Celsius a Fahrenheit es de\n" + String.format("%.2f", tempCambiada), "Convertido con exito", JOptionPane.INFORMATION_MESSAGE);
                }else if(BKelvin.isSelected()){
                    tempCambiada = (Double.parseDouble(IngresoTemperatura.getText()) + 273.15);
                    JOptionPane.showMessageDialog(this, "De Celsius a Kelvin es de\n" + String.format("%.2f", tempCambiada), "Convertido con exito", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(this, "La combinación no se puede hacer", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
                break;
            }case 2:{
                if(BFahrenheit.isSelected()){
                    tempCambiada = (Double.parseDouble(IngresoTemperatura.getText()) -273.15) * 9/5 + 32;
                    JOptionPane.showMessageDialog(this, "De Kelvin a Fahrenheit es de\n" + String.format("%.2f", tempCambiada), "Convertido con exito", JOptionPane.INFORMATION_MESSAGE);
                }else if(BCelsius.isSelected()){
                    tempCambiada = (Double.parseDouble(IngresoTemperatura.getText()) - 273.15);
                    JOptionPane.showMessageDialog(this, "De Kelvin a Celsius es de\n" + String.format("%.2f", tempCambiada), "Convertido con exito", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(this, "La combinación no se puede hacer", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
                break;
            }case 3:{
                JOptionPane.showMessageDialog(this, "La combinación no se puede hacer", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BConvertirActionPerformed

    private void EligeTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EligeTemperaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EligeTemperaturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BCelsius;
    private javax.swing.JButton BConvertir;
    private javax.swing.JRadioButton BFahrenheit;
    private javax.swing.JRadioButton BKelvin;
    private javax.swing.JRadioButton BRadianes;
    private javax.swing.JComboBox<String> EligeTemperatura;
    private javax.swing.JTextField IngresoTemperatura;
    private javax.swing.JLabel TextoGrados;
    private javax.swing.JLabel TextoTemperatura;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
